
SELECT DISTINCT (ID_PuntoVenta) AS 'VISTAS CREACIÓN' FROM INVENTARIO_MOVIMIENTOS WHERE Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND Movimiento = 'FACTURA POS' OR Movimiento = 'FACTURA INSTITUCIONAL' 


--[GENERAL]-------------------------------------------------------------------------------se hizo cambio

ALTER VIEW ClasificacionABCprecios AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
    JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV0', 'PdeV1') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL'  and REFERENCIAS.Servicio='0' GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientos AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV0', 'PdeV1') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL'  and REFERENCIAS.servicio = '0' GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


--[PdeV0]--------------------------------------------------------------------------------

ALTER VIEW ClasificacionABCpreciosPdeV0 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
        JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV0') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia

ALTER VIEW ClasificacionABCMovimientosPdeV0 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV0') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV1]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV1 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV1') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia

ALTER VIEW ClasificacionABCMovimientosPdeV1 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV1') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV2]--------------------------------------------------------------------------------



ALTER VIEW ClasificacionABCpreciosPdeV2 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV2') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV2 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV2') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    



--[PdeV3]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV3 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV3') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV3 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV3') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    
  


--[PdeV4]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV4 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV4') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV4 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV4') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    



--[PdeV5]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV5 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia) 
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV5') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV5 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV5') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV6]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV6 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV6') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV6 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV6') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    



--[PdeV7]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV7 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV7') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV7 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV7') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    

--[PdeV8]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV8 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV8') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV8 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV8') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV9]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV9 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV9') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV9 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV9') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    




--[PdeV10]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV10 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV10') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV10 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV10') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    

--[PdeV11]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV11 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV11') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV11 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV11') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    

--[PdeV12]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV12 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV12') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV12 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia) 
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV12') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV13]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV13 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV13') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia


ALTER VIEW ClasificacionABCMovimientosPdeV13 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV13') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV14]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV14 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV14') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV14 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV14') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV15]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV15 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV15') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV15 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV15') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    

--[PdeV16]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV16 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV16') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia




ALTER VIEW ClasificacionABCMovimientosPdeV16 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV16') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    



--[PdeV17]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV17 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV17') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV17 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV17') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    



--[PdeV18]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV18 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV18') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia



ALTER VIEW ClasificacionABCMovimientosPdeV18 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV18') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    


--[PdeV19]--------------------------------------------------------------------------------


ALTER VIEW ClasificacionABCpreciosPdeV19 AS 
SELECT 
    INVENTARIO_MOVIMIENTOS.REFERENCIA, 
    SUM(INVENTARIO_MOVIMIENTOS.Cantidad * INVENTARIO_MOVIMIENTOS.PrecioVenta) AS PRECIO
FROM 
    INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV19') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia




ALTER VIEW ClasificacionABCMovimientosPdeV19 AS 
SELECT INVENTARIO_MOVIMIENTOS.REFERENCIA, 
SUM(INVENTARIO_MOVIMIENTOS.Cantidad) AS CANTIDAD
FROM INVENTARIO_MOVIMIENTOS 
JOIN REFERENCIAS on (REFERENCIAS.Referencia = INVENTARIO_MOVIMIENTOS.Referencia)
WHERE INVENTARIO_MOVIMIENTOS.Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND ID_PuntoVenta IN ('PdeV19') AND INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA POS' OR INVENTARIO_MOVIMIENTOS.Movimiento = 'FACTURA INSTITUCIONAL' and REFERENCIAS.Servicio='0'  GROUP BY INVENTARIO_MOVIMIENTOS.Referencia    




















