--[CUNSULTA PDEV A LOS QUE EJECUTARLES ABC]--------------------------------------------------------------------------------

SELECT DISTINCT (ID_PuntoVenta) AS 'VISTAS CREACIÓN' FROM INVENTARIO_MOVIMIENTOS WHERE Fecha BETWEEN DATEADD(SECOND, -1, DATEADD(DAY, DATEDIFF(DAY, 0, DATEADD(MONTH, -3, GETDATE())) + 1, 0)) AND DATEADD(day, -1, DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()) + 1, 0)) AND Movimiento = 'FACTURA POS' OR Movimiento = 'FACTURA INSTITUCIONAL' 


--[GENERAL]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACION = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACION = (SELECT Clasificacion FROM Clasificacion_Final_ABC_Precios WHERE Clasificacion_Final_ABC_Precios.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_Precios);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACION = CLASIFICACION + (SELECT Clasificacion FROM Clasificacion_Final_ABC_Movimientos WHERE Clasificacion_Final_ABC_Movimientos.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_Movimientos);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACION = CLASIFICACION + 'B' WHERE LEN(CLASIFICACION) = 1;

--[PdeV0]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV0 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV0 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV0 WHERE Clasificacion_Final_ABC_PreciosPdeV0.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV0);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV0 = CLASIFICACIONPdeV0 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV0 WHERE Clasificacion_Final_ABC_MovimientosPdeV0.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV0);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV0 = CLASIFICACIONPdeV0 + 'B' WHERE LEN(CLASIFICACIONPdeV0) = 1;

--[PdeV1]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV1 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV1 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV1 WHERE Clasificacion_Final_ABC_PreciosPdeV1.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV1);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV1 = CLASIFICACIONPdeV1 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV1 WHERE Clasificacion_Final_ABC_MovimientosPdeV1.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV1);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV1 = CLASIFICACIONPdeV1 + 'B' WHERE LEN(CLASIFICACIONPdeV1) = 1;

--[PdeV2]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV2 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV2 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV2 WHERE Clasificacion_Final_ABC_PreciosPdeV2.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV2);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV2 = CLASIFICACIONPdeV2 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV2 WHERE Clasificacion_Final_ABC_MovimientosPdeV2.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV2);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV2 = CLASIFICACIONPdeV2 + 'B' WHERE LEN(CLASIFICACIONPdeV2) = 1;

--[PdeV3]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV3 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV3 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV3 WHERE Clasificacion_Final_ABC_PreciosPdeV3.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV3);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV3 = CLASIFICACIONPdeV3 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV3 WHERE Clasificacion_Final_ABC_MovimientosPdeV3.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV3);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV3 = CLASIFICACIONPdeV3 + 'B' WHERE LEN(CLASIFICACIONPdeV3) = 1;

--[PdeV4]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV4 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV4 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV4 WHERE Clasificacion_Final_ABC_PreciosPdeV4.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV4);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV4 = CLASIFICACIONPdeV4 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV4 WHERE Clasificacion_Final_ABC_MovimientosPdeV4.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV4);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV4 = CLASIFICACIONPdeV4 + 'B' WHERE LEN(CLASIFICACIONPdeV4) = 1;

--[PdeV5]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV5 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV5 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV5 WHERE Clasificacion_Final_ABC_PreciosPdeV5.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV5);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV5 = CLASIFICACIONPdeV5 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV5 WHERE Clasificacion_Final_ABC_MovimientosPdeV5.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV5);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV5 = CLASIFICACIONPdeV5 + 'B' WHERE LEN(CLASIFICACIONPdeV5) = 1;

--[PdeV6]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV6 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV6 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV6 WHERE Clasificacion_Final_ABC_PreciosPdeV6.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV6);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV6 = CLASIFICACIONPdeV6 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV6 WHERE Clasificacion_Final_ABC_MovimientosPdeV6.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV6);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV6 = CLASIFICACIONPdeV6 + 'B' WHERE LEN(CLASIFICACIONPdeV6) = 1;

--[PdeV7]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV7 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV7 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV7 WHERE Clasificacion_Final_ABC_PreciosPdeV7.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV7);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV7 = CLASIFICACIONPdeV7 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV7 WHERE Clasificacion_Final_ABC_MovimientosPdeV7.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV7);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV7 = CLASIFICACIONPdeV7 + 'B' WHERE LEN(CLASIFICACIONPdeV7) = 1;

--[PdeV8]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV8 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV8 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV8 WHERE Clasificacion_Final_ABC_PreciosPdeV8.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV8);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV8 = CLASIFICACIONPdeV8 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV8 WHERE Clasificacion_Final_ABC_MovimientosPdeV8.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV8);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV8 = CLASIFICACIONPdeV8 + 'B' WHERE LEN(CLASIFICACIONPdeV8) = 1;

--[PdeV9]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV9 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV9 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV9 WHERE Clasificacion_Final_ABC_PreciosPdeV9.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV9);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV9 = CLASIFICACIONPdeV9 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV9 WHERE Clasificacion_Final_ABC_MovimientosPdeV9.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV9);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV9 = CLASIFICACIONPdeV9 + 'B' WHERE LEN(CLASIFICACIONPdeV9) = 1;

--[PdeV10]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV10 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV10 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV10 WHERE Clasificacion_Final_ABC_PreciosPdeV10.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV10);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV10 = CLASIFICACIONPdeV10 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV10 WHERE Clasificacion_Final_ABC_MovimientosPdeV10.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV10);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV10 = CLASIFICACIONPdeV10 + 'B' WHERE LEN(CLASIFICACIONPdeV10) = 1;

--[PdeV11]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV11 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV11 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV11 WHERE Clasificacion_Final_ABC_PreciosPdeV11.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV11);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV11 = CLASIFICACIONPdeV11 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV11 WHERE Clasificacion_Final_ABC_MovimientosPdeV11.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV11);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV11 = CLASIFICACIONPdeV11 + 'B' WHERE LEN(CLASIFICACIONPdeV11) = 1;

--[PdeV12]--------------------------------------------------------------------------------

SELECT STRING_AGG(CONCAT('''',ID,''''),',') FROM PUNTO_VENTA WHERE ENABLED ='1'

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV12 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV12 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV12 WHERE Clasificacion_Final_ABC_PreciosPdeV12.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV12);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV12 = CLASIFICACIONPdeV12 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV12 WHERE Clasificacion_Final_ABC_MovimientosPdeV12.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV12);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV12 = CLASIFICACIONPdeV12 + 'B' WHERE LEN(CLASIFICACIONPdeV12) = 1;

--[PdeV13]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV13 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV13 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV13 WHERE Clasificacion_Final_ABC_PreciosPdeV13.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV13);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV13 = CLASIFICACIONPdeV13 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV13 WHERE Clasificacion_Final_ABC_MovimientosPdeV13.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV13);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV13 = CLASIFICACIONPdeV13 + 'B' WHERE LEN(CLASIFICACIONPdeV13) = 1;

--[PdeV14]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV14 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV14 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV14 WHERE Clasificacion_Final_ABC_PreciosPdeV14.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV14);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV14 = CLASIFICACIONPdeV14 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV14 WHERE Clasificacion_Final_ABC_MovimientosPdeV14.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV14);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV14 = CLASIFICACIONPdeV14 + 'B' WHERE LEN(CLASIFICACIONPdeV14) = 1;

--[PdeV15]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV15 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV15 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV15 WHERE Clasificacion_Final_ABC_PreciosPdeV15.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV15);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV15 = CLASIFICACIONPdeV15 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV15 WHERE Clasificacion_Final_ABC_MovimientosPdeV15.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV15);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV15 = CLASIFICACIONPdeV15 + 'B' WHERE LEN(CLASIFICACIONPdeV15) = 1;

--[PdeV16]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV16 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV16 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV16 WHERE Clasificacion_Final_ABC_PreciosPdeV16.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV16);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV16 = CLASIFICACIONPdeV16 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV16 WHERE Clasificacion_Final_ABC_MovimientosPdeV16.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV16);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV16 = CLASIFICACIONPdeV16 + 'B' WHERE LEN(CLASIFICACIONPdeV16) = 1;

--[PdeV17]--------------------------------------------------------------------------------

--[PdeV18]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV18 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV18 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV18 WHERE Clasificacion_Final_ABC_PreciosPdeV18.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV18);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV18 = CLASIFICACIONPdeV18 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV18 WHERE Clasificacion_Final_ABC_MovimientosPdeV18.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV18);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV18 = CLASIFICACIONPdeV18 + 'B' WHERE LEN(CLASIFICACIONPdeV18) = 1;

--[PdeV19]--------------------------------------------------------------------------------

--PRIMER UPDATE 
UPDATE REFERENCIAS SET CLASIFICACIONPdeV19 = 'C'
--UPDATE PRECIOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV19 = (SELECT Clasificacion FROM Clasificacion_Final_ABC_PreciosPdeV19 WHERE Clasificacion_Final_ABC_PreciosPdeV19.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_PreciosPdeV19);
--UPDATE MOVIMIENTOS
UPDATE REFERENCIAS SET CLASIFICACIONPdeV19 = CLASIFICACIONPdeV19 + (SELECT Clasificacion FROM Clasificacion_Final_ABC_MovimientosPdeV19 WHERE Clasificacion_Final_ABC_MovimientosPdeV19.REFERENCIA = REFERENCIAS.REFERENCIA) WHERE REFERENCIA IN (SELECT REFERENCIA FROM Clasificacion_Final_ABC_MovimientosPdeV19);
--SEGUNDO UPDATE
UPDATE REFERENCIAS SET CLASIFICACIONPdeV19 = CLASIFICACIONPdeV19 + 'B' WHERE LEN(CLASIFICACIONPdeV19) = 1;



















